name: haymanot_aweke
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_secure_storage:
  http:
  flutter_bloc: ^9.1.1
  socket_io_client: ^3.1.2
  dio: ^5.9.0
  image_picker: ^1.1.2
  path: ^1.9.1
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  get_it: ^8.1.0
  lints: ^5.0.0
  mockito: ^5.5.0
  build_runner: ^2.6.0
  internet_connection_checker: ^3.0.1
  shared_preferences: 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: CaveatBrush
      fonts:
        - asset: assets/fonts/CaveatBrush-Regular.ttf
